spring:
  application:
    name: Zhangyu_Passbook
  datasource:
    url: jdbc:mysql://127/0/0/1:3306/passbook?autoReconnect=true
    username: root
    password: zyzzhkht
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 127.0.0.1:2181
      rootDir: file:///Users/zhanghu05/QinyiZhang/Soft/hbase_data/root_dir
      nodeParent: /hbase
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 9528
logging:
  file: zhangyu-passbook.log
  level: debug
